channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - h5py=3.1.0
  - matplotlib=3.3.0
  - numpy=1.19.1
  - opencv=4.4.0
  - pandas=1.1.3
  - pillow=7.2.0
  - python=3.7.8
  - pytorch=1.6.0
  - rasterio=1.1.5  
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - torchvision=0.7.0
  - tqdm=4.48.2
